### ISSUE TITLE
Missing Electron packages

### ISSUE THREAD

**Issue by stweyel** [thenewboston-developers/Account-Manager#586]
After successful `npm install` i get some errors when trying to `npm start`:

```
An unhandled rejection has occurred inside Forge:
Error: Could not find any Electron packages in devDependencies
    at getElectronModuleName (/xxx/Account-Manager/node_modules/@electron-forge/core/src/util/electron-version.ts:56:11)
    at getElectronVersion (/xxx/Account-Manager/node_modules/@electron-forge/core/src/util/electron-version.ts:92:23)
    at _default (/xxx/Account-Manager/node_modules/@electron-forge/core/src/api/package.ts:186:28)
    at /xxx/Account-Manager/node_modules/@electron-forge/cli/src/electron-forge-package.ts:30:3

Electron Forge was terminated. Location:
{}
```
Specs: MacOS 10.12.6, Node 14.15.5, thenewboston@1.0.0-alpha.43

**Comment by angle943** [comment]
@stweyel hmm thats strange. I have the same Node version and the app version. My Mac OS is 11.2.1, but I don't think thats the issue.

Try deleting your `node_modules` directly, and doing `npm install && npm start` again?

Has anyone else been encountering this issue?
